[versions]
fabric-loader = "0.19.5"
gizmo = "1.1.1"
minecraft = "26.3"
neoforge = "26.3.0.16-beta"
neoform = "26.3-1"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
gizmo-common = { module = "me.m56738.gizmo:gizmo-common", version.ref = "gizmo" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Needed to make Renovate detect the version
#noinspection UnusedVersionCatalogEntry
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
#noinspection UnusedVersionCatalogEntry
neoform = { module = "net.neoforged:neoform", version.ref = "neoform" }
