[versions]
fabric-api = "0.155.2+26.2"
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
gizmo = "1.0.0"
minecraft = "26.2"
moddev = "2.0.142"
neoforge = "26.2.0.32-beta"
neoform = "26.2-2"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
gizmo-common = { module = "me.m56738.gizmo:gizmo-common", version.ref = "gizmo" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
